---
title: "Tarea 2"
author: "Silvana Morocho"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

# Installation y carga de paquetes

if(!require(devtools)) install.packages("devtools")
devtools::install_github("gualapuromoises/residualR")

# Distribution
library(residualR)

# Requiere paquete ggplot2

set.seed(1133)
potencia(4,2)

```


```{r}
# Carga de librería
library(dplyr)

# Crear los datos de los voluntarios
Voluntarios <- data.frame(
  Numero = paste("#", seq(2, 22, by = 2)),
  Edad = sample(16:19, 11, replace = TRUE),
  Calificacion = sample(1:10, 11, replace = TRUE),
  Genero = sample(c("Femenino", "Masculino", "No binario"), 11, replace = TRUE),
  Materia = sample(c("Biologia", "Genetica", "Quimica", "Biorreactores"), 11, replace = TRUE)
)

# Mostrar el marco de datos
Voluntarios

# Función para calcular los promedios de edad, calificación e IMC según género
calculo_promedios <- function(data){
  
  # Agregar variables de altura y peso
  new_data <- data %>%
    mutate(Altura = sample(150:190, nrow(data), replace = TRUE),
           Peso = sample(50:90, nrow(data), replace = TRUE))
  
  # Calcular el IMC de los voluntarios
  new_data$IMC <- new_data$Peso / ((new_data$Altura/100)^2)
  
  # Calcular la edad promedio y la calificación promedio según género
  promedios <- new_data %>%
    group_by(Genero) %>%
    summarize(promedio_edad = mean(Edad, na.rm = TRUE),
              promedio_calificacion = mean(Calificacion, na.rm = TRUE),
              promedio_IMC = mean(IMC, na.rm = TRUE))
  
  return(promedios)
}

# Llamada a la función para calcular los promedios
calculo_promedios(Voluntarios)

# Función para calcular la calificación promedio de los voluntarios
promedio <- function(x){
  return(mean(x, na.rm = TRUE))
}

# Llamada a la función para calcular la calificación promedio
promedio(Voluntarios$Calificacion)

# Gráfico de barras que muestra las calificaciones de cada voluntario
barplot(Voluntarios$Calificacion, 
        main = "Calificaciones", 
        col = rainbow(20), 
        border = "brown3", 
        xlim = c(0, 20), ylim = c(0, 20),
        xlab = "Voluntario", ylab = "Calificacion")

```



       
       
       
       
       
       
     
     
     